[tool.black]
line-length = 100

[tool.isort]
profile = "black"
multi_line_output = 3


[tool.pytest.ini_options]
log_cli = 1
addopts = "-rA -s --strict-markers -m 'local_test'"
markers = [
    "local_test: marks tests as local_test that will NOT run on CI/CD (deselect with '-m \"not local_test\"')",
]
