---
# This defines the name of the GitHub Actions workflow.
name: Checkout repo with python 3.10

# Specifies when this workflow should be triggered.
# In this case, it's triggered on pull requests targeting the 'main' branch.
on:
  pull_request:
    branches:
    - main

# This is the start of defining the jobs that the workflow will run.
jobs:
  # A unique ID for this job. This is 'checkout_repo_and_install' but can be any string.
  checkout_repo_and_install:
    # Specifies on which operating system the job should run.
    # It creates a virtual environment with this OS.
    runs-on: ubuntu-latest

    # Defines the steps that the job will execute.
    steps:
    # Checks out your repository under $GITHUB_WORKSPACE, so your workflow can access it.
    - name: Checkout Repository
      uses: actions/checkout@v3

    # This sets up the specified version of Python in the environment.
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # Runs a shell command to install the project's dependencies.
    - name: Install Dependencies
      run: pip install -r requirements.txt
