---
name: Checkout repo with python 3.10

on:
  pull_request:
    branches:
    - main

jobs:
  checkout_repo_and_install:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: pip install -r requirements.txt
